# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "julia"
    directory: "/"
    exclude-paths: # do not bother with [compat] for these
      - "/docs"
      - "/test"
    schedule:
      interval: "weekly"
