name = "MIRTio"
uuid = "274281c4-ae57-11e9-2014-65d3d5d9358c"
authors = ["fessler@umich.edu <fessler@umich.edu>"]
version = "0.4"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
HDF5 = "0.17"
julia = "1.10"
